IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUX_NAVIGATEITEM_T')
DROP TABLE CUX_NAVIGATEITEM_T
CREATE TABLE [dbo].[CUX_NAVIGATEITEM_T](
	[id] [int] IDENTITY(1,1) NOT NULL,
	parent int,
	title varchar(100) NOT NULL,
	icon varchar(100), 
	spread int, --0, 1
	url varchar(100),
	type int, --0 top, 1 left
	PRIMARY KEY CLUSTERED
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUX_NAVIGATEAUTHORITY_T')
DROP TABLE CUX_NAVIGATEAUTHORITY_T
CREATE TABLE CUX_NAVIGATEAUTHORITY_T(
	[id] [int] IDENTITY(1,1) NOT NULL,
	navigator_item_id int NOT NULL,
	role int,
	PRIMARY KEY CLUSTERED
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);



--测试用户DCSUP06
IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUX_USREREQUEST_T')
DROP TABLE CUX_USREREQUEST_T
CREATE TABLE CUX_USREREQUEST_T(
	[id] [int] IDENTITY(1,1) NOT NULL,
	usageId int not null,
	requestTime datetime,
	responseTime datetime,
	url varchar(200),
	isAjax int,
	PRIMARY KEY CLUSTERED
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

--测试用户DCSUP06
IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUX_USREUSAGE_T')
DROP TABLE CUX_USREUSAGE_T
CREATE TABLE CUX_USREUSAGE_T(
	[id] [int] IDENTITY(1,1) NOT NULL,
	userName varchar(100),
	loginTime datetime,
	logoutTime datetime,
	lastAccessedTime datetime,
	ip varchar(100),
	PRIMARY KEY CLUSTERED
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);
