IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUX_FAVOURITE_T')
DROP TABLE CUX_FAVOURITE_T
CREATE TABLE [dbo].[CUX_FAVOURITE_T](
	[id] [int] IDENTITY(1,1) NOT NULL,
  itemId int,
  createTime date
	PRIMARY KEY CLUSTERED
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);
